# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_main.custom_exception:
      class: AppBundle\EventListener\ExceptionListener
      arguments: ["@logger"]
      tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        - { name: monolog.logger, channel: exception }
        
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }    