<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GiveawayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiveawayRepository extends EntityRepository
{
    /**
      * Function to giveaways.
      *
      * @param string $name
      * @param string $sort
      *
      * @return object
      */
     public function fetchGiveaways($name,$sort)
     {
         $qb = $this->createQueryBuilder('give_away')
                   ->where('give_away.name LIKE :key')
                   ->setParameter('key', '%' . $name . '%')
                   ->orderBy('give_away.price', $sort)
                ;

         return $qb->getQuery()->getResult();
     }
}
